<Project Sdk="Microsoft.NET.Sdk">
  <!-- Contracts of the Dictionary plugin. -->
  <PropertyGroup>
    <RootNamespace>SuperMemoAssistant.Plugins.Dictionary.Interop</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\Interop\src\SuperMemoAssistant.Interop\SuperMemoAssistant.Interop.csproj" />
    <ProjectReference Include="$(RepoRoot)libs\PluginManager\src\PluginManager.Interop\PluginManager.Interop.csproj" />
    <ProjectReference Include="$(RepoRoot)libs\Extensions.System.IO\src\Extensions.System.IO.csproj" />
  </ItemGroup>
</Project>